"""Altered activities table

Revision ID: ddc30608f593
Revises: 788c904a4a56
Create Date: 2023-04-18 21:11:11.498318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc30608f593'
down_revision = '788c904a4a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('hours', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('minutes', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'time_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('time_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'activities', 'times', ['time_id'], ['id'])
    op.drop_column('activities', 'minutes')
    op.drop_column('activities', 'hours')
    # ### end Alembic commands ###
